### ISSUE TITLE
Heat loss calculation

### ISSUE THREAD

**Issue by deku-m** [marcoboers/home-assistant-quatt#67]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/quatt/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Well i think when most people in HA using this integration would like to find out if there heatloss is ok according the setting they had in their energy loss. So they can check and monitor...

### Describe the solution you'd like

Calculate the heat loss according the history?

### Describe alternatives you've considered

There is a document on tweakers that someone created in excel not sure we can make it so in HA so you can see it there?

### Additional context

-

**Comment by marcoboers** [comment]
Could you provide a link to the spreadsheet?

**Comment by deku-m** [comment]
> Could you provide a link to the spreadsheet?

https://gathering.tweakers.net/forum/view_message/77395714

Thats what i found on tweakers.

**Comment by marcoboers** [comment]
I think this is out of scope for this integration since it contains data not provided by the local API.For example the API gives power instead of energy total and I do not know how to do the integration/riemann sum within the integration. Also, gas usage is not accessable within the API.

I think a blueprint might be an option but I am not sure. It could have the input sensors configurable and calculate it once per day. But doing it in an automation would then be a first step.
